### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by dtitov** [NBISweden/LocalEGA-deploy-swarm#12]
### Description
We would like to set up a so-called "staging environment": a place where LocalEGA will be running permanently in a production-like setup (Norwegian production-like setup, to be precise). 

This should include:
- [x] Network separation
- [x] Machines' firewalls configuration (to simulate TSD restrictions)
- [x] Linking it to Jenkins pipeline so that Docker images in this environment are automatically updated on successful integrated builds. 

### Definition of Done
Having a working environment in OpenStack.

### How to test
Manual smoke-testing.

**Comment by juhtornr** [comment]
Time estimate: 3 days
